function setFIGUREproperties(HOR,VER,SCALE,X0,Y0)

if nargin<1;HOR=21*35;end
if nargin<2;VER=29*35;end
if nargin<3;SCALE=35;end
if nargin<4;X0=70;end
if nargin<5;Y0=70;end

set(gcf,'PaperOrientation','portrait', ...
        'PaperPosition',[0 0 HOR/SCALE VER/SCALE], ...
        'PaperSize',[HOR/SCALE VER/SCALE], ...
        'Position',[X0,Y0,HOR,VER], ...
        'PaperUnits','centimeters', ...
        'PaperPositionMode','manual', ...
        'PaperType','a4letter'); 
        